src_31.tap

diff --git a/usr/src/cmd/.cmd-3b2/askx b/usr/src/cmd/.cmd-3b2/askx
--- a/usr/src/cmd/.cmd-3b2/askx
+++ b/usr/src/cmd/.cmd-3b2/askx
@@ -1,4 +1,4 @@
-#ident	"@(#)cmd-3b2:askx	1.2"
+#ident	"@(#)cmd-3b2:askx	1.3"
 #
 # ask
 #
@@ -142,26 +142,26 @@ do
 				exit 0
 			fi
 		done
-		echo "\nInvalid response ... please enter one of:" >&2
+		echo "\nInvalid response ... please enter one of the following:" >&2
 		if [ -n "${num_min}" ]
 		then
-			echo "\to A number from ${num_min} thru ${num_max}" >&2
+			echo "\t A number from ${num_min} thru ${num_max}" >&2
 		fi
 		if [ ${aflag:-n} = y ]
 		then
-			echo "\to A string made up of letters, numbers, '-', '_' and '.'" >&2
+			echo "\t A string made up of letters, numbers, '-', '_' and '.'" >&2
 		fi
 		if [ ${pflag:-n} = y ]
 		then
-			echo "\to An absolute pathname (\"/name[/name ...]\")" >&2
+			echo "\t An absolute pathname (\"/name[/name ...]\")" >&2
 		fi
 		for x in ${choice}
 		do
-			echo "\to ${x}" >&2
+			echo "\t ${x}" >&2
 		done
 		if [ -n "${help}" ]
 		then
-			echo "\to help" >&2
+			echo "\t help" >&2
 		fi
 	done
 done
diff --git a/usr/src/cmd/sadmin/admin/checkfsys b/usr/src/cmd/sadmin/admin/checkfsys
--- a/usr/src/cmd/sadmin/admin/checkfsys
+++ b/usr/src/cmd/sadmin/admin/checkfsys
@@ -1,4 +1,4 @@
-#ident	"@(#)sadmin:admin/checkfsys	2.7"
+#ident	"@(#)sadmin:admin/checkfsys	2.10"
 #	Copyright (c) 1984 AT&T.  All Rights Reserved.
 #	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T.
 #	The copyright notice above does not evidence any actual
@@ -61,13 +61,24 @@ then
 You may remove the medium.'
 	exit 0
 fi
-
+ERR=0
+if [ -f /${fsname} ]
+	then
+		ERR=2
+	elif [ -d /${fsname} ]
+	then
+	mounted=`/etc/mount | sed 's; .*;;'`
+	if echo "$mounted" | grep "/${fsname}\$"
+	then
+		ERR=3
+	fi
+fi
 checktype=`checklist ${flags} -fep -H '
 	The "check" looks for file system damage but does not attempt to
 	fix it.  The "interactive repair" asks you to decide what should be
 	done for each error.  The "automatic repair" makes standard repairs
-	when it finds errors.  "automatic" generally safe, although there are
-	some problems it cannot handle.  In those cases you need a file system
+	when it finds errors;  it is generally safe, although there are some 
+	problems it cannot handle.  In those cases, you need a file system
 	repair expert to fix things.
 	     Most users will be satisfied using "automatic".  For particularly
 	sensitive or unreproducible data we recommend that you use "check"
@@ -109,11 +120,26 @@ then
 	representative if you think there is a machine problem.
 You may now remove the medium."
 else
+	if [ $ERR -ne 0 ]
+	then
+		echo "\tUnable to mount file system '${fsname}' to complete checking."
+		case "$ERR" in
+		"2") echo "\tA file by that name already exists in the root directory."
+			;;
+		"3") echo "\tA file system with that name is already mounted."
+			;;
+		*) echo "\tUnknown error $ERR."
+			;;
+		esac
+	  exit 1
+	fi
+
 	trap "	trap '' 1 2
 		diskumount -n '${ndrive}' ${ddrive}" 0
 	/etc/mount ${ddrive} /${fsname} -r
 	if [ ! -d /${fsname}/lost+found ]
 	then
+		echo "There is no lost+found directory on file system '${fsname}'"
 		exit 0
 	fi
 	cd /${fsname}/lost+found
diff --git a/usr/src/cmd/sadmin/admin/menu/filemgmt/restore b/usr/src/cmd/sadmin/admin/menu/filemgmt/restore
--- a/usr/src/cmd/sadmin/admin/menu/filemgmt/restore
+++ b/usr/src/cmd/sadmin/admin/menu/filemgmt/restore
@@ -1,4 +1,4 @@
-#ident	"@(#)sadmin:admin/menu/filemgmt/restore	2.9"
+#ident	"@(#)sadmin:admin/menu/filemgmt/restore	2.15"
 #menu# restore files from "backup" & "store" media to built-in disk
 #help# 
 #help#	Restore copies files from media made by "backup" and "store"
@@ -18,7 +18,9 @@ rnamewarn='WARNING:
 	Remember that only the first 14 characters of each part of the
 	file name (i.e. the characters between the "/"s) are significant.
 You will be asked to rename each file in turn.  An empty response skips that
-file.  An answer of "." (period) restores the file with its original name.'
+file.  An answer of "." (period) restores the file with its original name.
+If you do not specify a full pathname, the file will be restored under
+/tmp or /usr/tmp (a message will tell you where to find it).'
 
 dir=${0}.d
 if [ -d ${dir} ]
@@ -27,8 +29,11 @@ then
 else
 	patterns=
 fi
-ncpiocmd=ncpio
-ncpioargs=
+cpiocmd=cpio
+cpioargs=
+
+ncpiocmd=${cpiocmd}	# for backward compatibility
+ncpioargs=${cpioargs}
 
 ddrive=`selectdevice -c $$ /dev/rSA ${patterns}`
 ndrive=`drivename ${ddrive}`
@@ -38,8 +43,16 @@ then
 	. ${dir}/`selpattern ${ddrive}`
 fi
 
-cd /
+if [ -d /usr/tmp ]
+then
+	SA_TMP=/usr/tmp/SA$$
+else
+	SA_TMP=/tmp/SA$$
+fi
+mkdir $SA_TMP
+cd $SA_TMP
 
+ERR=0
 while true
 do
 	type=`checklist ${flags} -fe -H'
@@ -67,8 +80,10 @@ Enter a number [?, q]:' 1 2 3 4`
 			case "${type}" in
 			1 )	# single file
 				sfile=`checkre ${flags} -fe -l ' ' -H '
-	You may also specify the file names as cpio(1) patterns and you
-	may specify more than one file name.
+	You may specify more than one file name (for example,
+	/dir/file1 /dir/file2 ). You may also specify the file 
+	names as cpio(1) patterns (for example, /dir/file? or /dir/f* ).
+
 	If you do not find files that you expect to find, use Option 4 to
 	list out all the file names on the media.  Entering file names
 	exactly as they exist on the list will always work.' \
@@ -81,6 +96,18 @@ Enter a number [?, q]:' 1 2 3 4`
 	'/[^/]\{1,14\}$' 'No more than 14 characters in a file name.'  |
 				sed "/./s;.*;'&';"  |
 				tr '\012' ' '`
+				cpio -ict < "${ddrive}" > /tmp/restore$$ 2>/dev/null
+				for n in `echo ${sfile} | tr -d "\'"`
+				do
+				if [ `grep -c "${n}\$" /tmp/restore$$` -eq 0 ]
+				then
+					echo "\n\tFile does not exist on medium."
+					ERR=1
+				fi
+				done
+				rm -f /tmp/restore$$
+				if [ $ERR -eq 0 ]
+				then
 				if  checkyn ${flags} -f 'Do you want to rename each file as it is copied in?'
 				then
 					echo "${rnamewarn}"
@@ -92,8 +119,12 @@ Enter a number [?, q]:' 1 2 3 4`
 				#  Magic here!  We must keep the shell from
 				#  interpreting meta-characters that may be in
 				#  ${sfile}.
-				eval ${ncpiocmd} ${ncpioargs} \
-					-icdu ${rflag} -I${ddrive} "${sfile}"
+				eval ${cpiocmd} ${cpioargs} \
+					-icdu ${rflag} -I${ddrive} "${sfile}" 2>/dev/null
+				if [ $? -ne 0 ]
+				then ERR=2
+				fi
+				fi
 				;;
 			2 )	# a directory
 				sfile=`checkre ${flags} -fe -l ' ' \
@@ -106,6 +137,9 @@ Enter a number [?, q]:' 1 2 3 4`
 	'/[^/]\{1,14\}$' 'No more than 14 characters in a file name.'  |
 				sed "/./s;.*;'&/*';"  |
 				tr '\012' ' '`
+				LIST=`cpio -ict 2>/dev/null < "${ddrive}" | eval grep -c "${sfile}/"`
+				if [ $LIST -gt 1 ]
+				then
 				if  checkyn ${flags} -f 'Do you want to rename each file as it is copied in?'
 				then
 					echo "${rnamewarn}"
@@ -117,8 +151,16 @@ Enter a number [?, q]:' 1 2 3 4`
 				#  Magic here!  We must keep the shell from
 				#  interpreting meta-characters that may be in
 				#  ${sfile}.
-				eval ${ncpiocmd} ${ncpioargs} \
-					-icdu ${rflag} -I${ddrive} "${sfile}"
+				eval ${cpiocmd} ${cpioargs} \
+					-icdu ${rflag} -I${ddrive} "${sfile}" 2>/dev/null
+				if [ $? -ne 0 ]
+					then ERR=2
+				fi
+				else
+					echo "\n\tDirectory does not exist on medium,"
+				 	echo "\tor it is empty (no files to restore)."
+					ERR=1
+				fi
 				;;
 			3 )	# entire contents
 				if  checkyn ${flags} -f 'Do you want to rename the files as they are copied in?'
@@ -128,8 +170,12 @@ Enter a number [?, q]:' 1 2 3 4`
 				else
 					rflag=-V
 				fi
-				${ncpiocmd} ${ncpioargs} \
+				${cpiocmd} ${cpioargs} \
 					-icdu ${rflag} -I${ddrive}
+				if [ $? -ne 0 ]
+				then
+					ERR=2
+				fi
 				;;
 			4 )	# list contents
 				if  checkyn -f 'Do you want to see the file status information, too?'
@@ -139,18 +185,32 @@ Enter a number [?, q]:' 1 2 3 4`
  mode  owner   size   date of last access	  filename
 ------ ------  -----  --------------------  --------------------'
 				fi
-				${ncpiocmd} ${ncpioargs} \
+				${cpiocmd} ${cpioargs} \
 					-ict ${rflag} -I${ddrive}
-				echo "You may now remove the medium from the ${ndrive}."
+				if [ $? -ne 0 ]
+					then ERR=2
+				fi
 				continue
 			esac
-			if [ $? = 0 ]
+			cd /
+			if [ $ERR -eq 0 ]
 			then
-				echo 'Restoration complete.'
+				rmdir $SA_TMP 2> /dev/null
+				if [ -d $SA_TMP ]
+				then
+					echo "Files stored in $SA_TMP if full pathname not specified."
+				fi
+			echo 'Restoration complete.'
 			else
-				echo '	Restoration did not work.
+				echo '\n\tWARNING: Restoration incomplete!
 	See the Owner/Operator manual for help.'
-				exit
+				if [ $ERR -eq 2 ]
+				then
+					echo "\n\tFailed while trying to recover file.  "
+					echo "\tRecovery may be possible using cpio(1) with the -k option."
+					echo "\tSee the User's Reference Manual for further information."
+				fi
+				exit 1
 			fi
 			echo "You may now remove the medium from the ${ndrive}."
 			continue
diff --git a/usr/src/cmd/sadmin/admin/menu/filemgmt/store b/usr/src/cmd/sadmin/admin/menu/filemgmt/store
--- a/usr/src/cmd/sadmin/admin/menu/filemgmt/store
+++ b/usr/src/cmd/sadmin/admin/menu/filemgmt/store
@@ -1,4 +1,4 @@
-#ident	"@(#)sadmin:admin/menu/filemgmt/store	2.7"
+#ident	"@(#)sadmin:admin/menu/filemgmt/store	2.11"
 #menu# store files and directories of files onto removable media
 #help# 
 #help#	Store copies files from the built-in disk to removable media and allows
@@ -15,8 +15,11 @@ then
 else
 	patterns=
 fi
-ncpiocmd=ncpio
-ncpioargs=
+cpiocmd=cpio
+cpioargs=
+
+ncpiocmd=${cpiocmd}		# for backward compatibility
+ncpioargs=${cpioargs}
 
 ddrive=`selectdevice -c $$ /dev/rSA ${patterns}`
 ndrive=`drivename ${ddrive}`
@@ -168,7 +171,7 @@ Insert the next medium into the ${ndrive}.
 Press <RETURN> when ready. [q] "
 
 # now write the files out to the floppy
-if  ${ncpiocmd} ${ncpioargs} -oac -M"${msg}" ${verbose} -O${ddrive} \
+if  ${cpiocmd} ${cpioargs} -oac -M"${msg}" ${verbose} -O${ddrive} \
 	</tmp/$$store1 
 then
 	echo 'Store complete.'
@@ -213,7 +216,7 @@ all parts that were just written to, starting with "part 1".
 
 	# generate table of contents and
 	# compare original list of files with table of contents
-	if  ${ncpiocmd} ${ncpioargs} -ict -I${ddrive} >/tmp/$$store2  &&
+	if  ${cpiocmd} ${cpioargs} -ict -I${ddrive} >/tmp/$$store2  &&
 	    diff -b /tmp/$$store1 /tmp/$$store2 
 	then
 		echo 'Verification complete.'
@@ -230,6 +233,12 @@ if  checkyn ${chkflags} -H'
 	be the copy that has just been stored.' \
 	-f 'Should the stored files be removed from the built-in disk?'
 then
-	sort -r </tmp/$$store1  |  xargs rm -rf
+	msg=`sort -r </tmp/$$store1  |  xargs rm -rf 2>&1`
+	echo $msg | grep mount
+	if [ $? -eq 0 ]
+	then
+		echo "Files removed, but '${fsname}' is a mounted file system"
+		echo "so directory '${fsname}' cannot be removed."
+	fi
 	echo 'Removal complete.'
 fi
diff --git a/usr/src/cmd/sadmin/etc/savecpio b/usr/src/cmd/sadmin/etc/savecpio
--- a/usr/src/cmd/sadmin/etc/savecpio
+++ b/usr/src/cmd/sadmin/etc/savecpio
@@ -1,4 +1,4 @@
-#ident	"@(#)sadmin:etc/savecpio	2.7"
+#ident	"@(#)sadmin:etc/savecpio	2.10"
 #	Mechanism to save file-systems in cpio format on removable media.
 
 #!	chmod +x ${file}
@@ -6,10 +6,10 @@
 complete=yes
 ddrive=/dev/diskette
 msg=
-ncpiocmd=ncpio
+cpiocmd=cpio
 ndrive='diskette drive'
 verbose=-V
-exit=
+exit=0
 while [ -n "$1" ]
 do
 	case "$1" in
@@ -34,6 +34,7 @@ do
 		if [ -z "${ndrive}" ]
 		then
 			echo >&2 "$0:  -n drive-name must be specified before -M msg"
+			exit=1
 			exit 1
 		fi
 		shift
@@ -45,12 +46,13 @@ Press <RETURN> when ready. [q] "
 	-C )
 		if [ -n "$2" ]
 		then
-			ncpiocmd=$2
+			cpiocmd=$2
 		fi
 		shift
 		;;
 	-* )
 		echo >&2 "$0:  illegal flag argument '$1'"
+		exit=1
 		exit 1
 		;;
 	* )
@@ -63,6 +65,7 @@ if [ $# -lt 1  -o  -z "${ddrive}"  -o  -z "${ndrive}" ]
 then
 	echo >&2 "Usage:  $0 -c|i -d device  -n device-name  \\
 	[ -v ] [ -M msg ] [ -C cmd ] file-system ..."
+	exit=1
 	exit 1
 fi
 
@@ -72,18 +75,16 @@ do
 	then
 		echo "$0:  ${d}:  Not a mounted file system."
 		exit=1
+		exit 1
 	fi
 done
-if [ ${exit} ]
-then
-	exit ${exit}
-fi
 mounted=`/etc/mount  |  grep " ${ddrive} "`
 if [ -n "${mounted}" ]
 then
 	echo "	A file system is still mounted on the ${ndrive}.
 ${mounted}
 	Save not performed.  Stop."
+	exit=1
 	exit 1
 fi
 
@@ -95,13 +96,14 @@ then
 fi
 cd ${SAVEDIR}/timestamp
 
-trap exit 1 2 15
-trap 'rm -f /tmp/$$.?.save ${SAVEDIR}/timestamp/$$*' 0
+trap 'exit=2; exit 2' 1 2 15
+trap 'rm -f /tmp/$$.?.save ; find ${SAVEDIR}/timestamp -name "$$*" -print | rm -f ; exit ${exit} ' 0
 
 if [ ${complete} ]
 then
 	for dir
 	{
+		NESTED=
 		if [ ${dir} = / ]
 		then
 			DIR=:root:
@@ -110,21 +112,34 @@ then
 			dirlist="${dirlist} `ls -d /*  |  fgrep -vx -f fgrep.tmp`"
 			rm -f fgrep.tmp
 		else
-			DIR=`expr "${dir}" : '/\(.*\)'`
+			DIR=`basename ${dir}`
+			if test "`dirname ${dir}`" != "/"
+			then
+				NESTED=`echo ${dir} | sed 's%/\([^/]*\)%/\1.d%g'`
+				NESTED=`dirname ${NESTED}`/
+				eval `echo ${dir} | sed 's%/\([^/]*\)\(.*\)%Parent=\1 Child=\2%'`
+				while test "${Parent}" != "${DIR}"
+				do
+					mkdir ${Parent}.d  2>/dev/null
+					cd ${Parent}.d
+					eval `echo ${Child} | sed 's%/\([^/]*\)\(.*\)%Parent=\1 Child=\2%'`
+				done
+			fi
+			cd ${SAVEDIR}/timestamp
 			dirlist="${dirlist} ${dir}"
 		fi
-		date +'%a. %D, %r' >$$${DIR}
+		date +'%a. %D, %r' > ${SAVEDIR}/timestamp/${NESTED}$$${DIR}
 	}
 
 	#	Finding and sorting in a loop allows for shorter sorts,
 	#	file systems are backed up in order requested, and
-	#	find of 2nd-thru-Nth file system overlaps with ncpio output.
+	#	find of 2nd-thru-Nth file system overlaps with cpio output.
 	#	find(1) output is sorted to make looking for file names easier.
 	for d in ${dirlist}
 	do
 		find ${d} -depth -print  |  sort
 	done  |
-		${ncpiocmd} -oac"${msg}" ${verbose} -O ${ddrive}
+		${cpiocmd} -oac"${msg}" ${verbose} -O ${ddrive}
 else
 	sed '	/^#/d
 		s/.*/\\;&;d/
@@ -132,6 +147,7 @@ else
 	>/tmp/$$.2.save
 	for dir
 	{
+		NESTED=
 		if [ ${dir} = / ]
 		then
 			DIR=:root:
@@ -140,19 +156,25 @@ else
 			dirlist=`ls -d /*  |  fgrep -vx -f fgrep.tmp`
 			rm -f fgrep.tmp
 		else
-			DIR=`expr "${dir}" : '/\(.*\)'`
+			DIR=`basename ${dir}`
+			if test "`dirname ${dir}`" != "/"
+			then
+				NESTED=`echo ${dir} | sed 's%/\([^/]*\)%/\1.d%g'`
+				NESTED=`dirname ${NESTED}`/
+			fi
 			dirlist=${dir}
 		fi
-		lastsave=`cat -s ${DIR}`
+		lastsave=`cat -s ${SAVEDIR}/timestamp/${NESTED}${DIR}`
 		if [ -z "${lastsave}" ]
 		then
-			echo >&2 "$0:  ${SAVEDIR}/timestamp/${DIR} does not exist or empty.
+			echo >&2 "$0:  \tCannot do incremental backup.
 			Complete backup ( ${cmd} -c ${dir} ) needs to be run first."
+			exit=1
 			exit 1
 		fi
 
-		date +'%a. %D, %r' >$$${DIR}
-		find ${dirlist} -depth -newer ${DIR} -print  |
+		date +'%a. %D, %r' >${SAVEDIR}/timestamp/${NESTED}$$${DIR}
+		find ${dirlist} -depth -newer ${SAVEDIR}/timestamp/${NESTED}${DIR} -print  |
 			sed -f /tmp/$$.3.save  |
 			sort >/tmp/$$.4.save
 		if [ ! -s /tmp/$$.4.save ]
@@ -170,13 +192,16 @@ else
 		exit
 	fi
 
-	${ncpiocmd} -oac"${msg}" ${verbose} -O ${ddrive} </tmp/$$.2.save
+	${cpiocmd} -oac"${msg}" ${verbose} -O ${ddrive} </tmp/$$.2.save
 fi
 if [ $? != 0 ]
 then
+	exit=1
 	exit 1
 fi
-for f in $$*
-{
-	mv -f ${f} `expr ${f} : "$$\(.*\)"`
-}
+for f in `find . -name "$$*" -print`
+do
+	FILE=`basename ${f} | sed "s/$$//"`
+	mv -f ${f} `dirname ${f}`/${FILE} 2>/dev/null
+done
+exit 0
diff --git a/usr/src/cmd/sadmin3b2/admin/menu/diskmgmt/harddisk/display b/usr/src/cmd/sadmin3b2/admin/menu/diskmgmt/harddisk/display
--- a/usr/src/cmd/sadmin3b2/admin/menu/diskmgmt/harddisk/display
+++ b/usr/src/cmd/sadmin3b2/admin/menu/diskmgmt/harddisk/display
@@ -1,4 +1,4 @@
-#ident	"@(#)sadmin3b2:admin/menu/diskmgmt/harddisk/display	1.5"
+#ident	"@(#)sadmin3b2:admin/menu/diskmgmt/harddisk/display	1.8"
 #menu# display hard disk partitioning
 #help# 
 #help#	Display the partitioning of a hard disk.  Also shows the
@@ -19,16 +19,26 @@ ndrive=`drivename ${ddrive}`
 . $DIRPATH/display.d/`basename $ddrive | sed s/[0-9]*$//p`
 
 dskname=`samedev ${ddrive} /dev/rdsk/c*d*s6`
-eval `basename ${dskname} | sed -e 's:^c\([0-9]*\)d\([0-9]*\).*$:slot=\1 drv=\2:'`
-slot=`expr ${slot} - 1`
-
-echo "Displaying ${ndrive} partitioning (hardware slot ${slot} drive ${drv}):\n"
-
-if /etc/prtvtoc ${ddrive}	
+dskname=`basename ${dskname}`
+havet=`expr ${dskname} : '.*\(t\).*'`
+if [ -n "${havet}" ]
 then
-	:
+  eval `echo ${dskname} | sed -e 's:^c\([0-9]*\)t\([0-9]*\)d\([0-9]*\).*$:slot=\1 tc=\2 drv=\3:'`
+  echo "Displaying ${ndrive} partitioning (hardware slot ${slot},"
+  echo "target controller ${tc}, drive ${drv}):\n"
 else
-	admerr $0 hard disk partitioning display failed.
+  eval `echo ${dskname} | sed -e 's:^c\([0-9]*\)d\([0-9]*\).*$:slot=\1 drv=\2:'`
+  slot=`expr ${slot} - 1`
+  echo "Displaying ${ndrive} partitioning (hardware slot ${slot} drive ${drv}):\n"
+fi
+
+/etc/prtvtoc ${ddrive}	
+if [ $? -ne 0 ]
+then
+	echo "\tDisplay of the hard disk partitioning failed."
+	echo "\tSuggestions:  1) The disk may not be partitioned."
+	echo "\t              2) There may be a problem with the hard disk itself."
+	echo "\t                 Call your service representative."
 	exit 1
 fi
 exit 0
diff --git a/usr/src/cmd/uucp/uupick b/usr/src/cmd/uucp/uupick
--- a/usr/src/cmd/uucp/uupick
+++ b/usr/src/cmd/uucp/uupick
@@ -1,4 +1,4 @@
-#ident	"@(#)uucp:uupick	2.4"
+#ident	"@(#)uucp:uupick	2.6"
 
 # sys: system; user: login name;  cdir: current directory;
 # tdir: temporary directory; pu: PUBDIR/receive/user;
@@ -9,10 +9,10 @@ sys=""
 var=""
 varto=""
 varfrom=""
-trap "exit" 1 2 13 15
+trap "exit 1" 1 2 13 15
 # get options
 if test $# -gt 2
-then echo "Usage: $0 [-s sysname]"; exit
+then echo "Usage: $0 [-s sysname]"; exit 1
 fi
 while test $# -ge 1
 do
@@ -24,15 +24,19 @@ do
 			sys=$2
 			shift
 		fi
+		if [ -z "$sys" ]
+		then
+	 		echo "Usage: $0 [-s sysname]"; exit 1
+		fi
 		;;
-	 *)    echo "Usage: $0 [-s sysname]"; exit
+	 *)    echo "Usage: $0 [-s sysname]"; exit 1
 	esac
 	shift
 done
 user=`id | sed -n "/^uid=[0-9]*(\([^)]*\)).*/s//\1/p"`
 
 if test -z "$user"
-then echo "User id required!"; exit
+then echo "User id required!"; exit 1
 fi
 
 pu=/usr/spool/uucppublic/receive/$user
@@ -50,12 +54,12 @@ do
 		do
 			if test $j = "." -o $j = ".."; then continue; fi
 			if test -d $j
-			then echo "from system $i: directory $j"
-			else echo "from system $i: file $j"
+			then echo "from system $i: directory $j \c"
+			else echo "from system $i: file $j \c"
 			fi
 			while true
 			do
-			  echo '?'
+			  echo '? \c'
 			  if read cmd dir
 			  then
 				trap ": ;;" 1
@@ -72,22 +76,29 @@ do
 				 	then abs=`expr "$dir" : '/.*'`
 						if test $abs != 0
 						then tdir=$dir
- 						elif test -d "$cdir/$dir"
-						then tdir=$cdir/$dir
+ 						else tdir=$cdir/$dir
 						fi
 					else
 						tdir=$cdir
 					fi
-					find $j -print |cpio -pdmuv $tdir \
-					1>> /tmp/$$uupick	
+					if [ ! -d $tdir -o ! -w $tdir ]; then
+					    echo "directory '$tdir' doesn't exist or isn't writable"
+					    continue
+					fi
+					find $j -depth -print >/tmp/$$uupick
+					cpio -pdmu $tdir </tmp/$$uupick 
 					for k in `cat /tmp/$$uupick`
 					do
-					    varto="$k"
-					    var=`echo $k |sed -n "s;^$tdir/;;p"`
-					    varfrom="$pu/$i/$var"
-					    cmp $varfrom $varto
-					    if test $? -eq 0; then
-					    	rm -fr $varfrom
+					    varto="$tdir/$k"
+					    varfrom="$pu/$i/$k"
+					    if test -f $varfrom; then
+						if cmp $varfrom $varto ; then
+					    	    rm -f $varfrom
+						else
+						    echo "file '$varfrom' not removed"
+						fi
+					    else
+						rmdir $varfrom 2>/dev/null
 					    fi
 					done
 					rm -f /tmp/$$uupick
@@ -96,34 +107,45 @@ do
 #put their names in /tmp/$$uupick.
 #Only remove those named files
 #from...receive/..dir if cmp
-#verifies transfer took place
+#verifies transfer took place.
+#then find & remove directories
+#(separate find is necessary because
+#cpio -v doesn't print dir names)
 				 a)	eval dir="$dir"
 					if test $dir
 					then abs=`expr "$dir" : '/.*'`
 						if test $abs != 0
-							then tdir=$dir
-						elif test -d "$cdir/$dir"
-							then tdir=$cdir/$dir
+						then tdir=$dir
+						else tdir=$cdir/$dir
 						fi
 					else
 						tdir=$cdir
 					fi
-					find * -print |\
-					cpio -pdmuv $tdir 1>> /tmp/$$uupick
+					if [ ! -d $tdir -o ! -w $tdir ]; then
+					    echo "directory '$tdir' doesn't exist or isn't writable"
+					    continue
+					fi
+					find . -depth -print | \
+					grep -v '^\.$' >/tmp/$$uupick
+					cpio -pdmu $tdir </tmp/$$uupick
 					for k in `cat /tmp/$$uupick`
 					do
-					    varto="$k"
-					    var=`echo $k |sed -n "s;^$tdir/;;p"`
-					    varfrom="$pu/$i/$var"
-					    cmp $varfrom $varto
-					    if test $? -eq 0; then
-					     	rm -fr $varfrom
+					    varto="$tdir/$k"
+					    varfrom="$pu/$i/$k"
+					    if test -f $varfrom; then
+						if cmp $varfrom $varto ; then
+						    rm -f $varfrom
+						else
+						    echo "file '$varfrom' not removed"
+						fi
+					    else
+						rmdir $varfrom 2>/dev/null
 					    fi
 					done
 					rm -f /tmp/$$uupick
 					break 2 ;;
 				 p)	if test -d $j
-					then find . -print
+					then find $j -print
 					elif test -s $j 
 				        then cat $j
 					fi ;;
@@ -137,7 +159,7 @@ do
 				 *)	echo "usage: [d][m dir][a dir][p][q]\c"
 					echo "[cntl-d][!cmd][*][new-line]" ;;
 				esac
-				trap 1
+				trap "exit 1" 1
 			  else	break 3
 			  fi
 			done
diff --git a/usr/src/lib/libcurses/screen/makefile b/usr/src/lib/libcurses/screen/makefile
--- a/usr/src/lib/libcurses/screen/makefile
+++ b/usr/src/lib/libcurses/screen/makefile
@@ -5,7 +5,7 @@
 #	The copyright notice above does not evidence any
 #	actual or intended publication of such source code.
 
-#ident	"@(#)curses:screen/makefile	1.31.1.7"
+#ident	"@(#)curses:screen/makefile	1.31.1.45"
 
 #
 # cursor package maker
@@ -18,10 +18,10 @@ SLIB=	libcurses.a
 MYBIN=	$(ROOT)/usr/bin
 USRLIB = $(ROOT)/usr/lib
 CTAGS=	ctags
-BUILT=	capnames.c term.h keycaps curses.h keyname.c initkeypad.c termcap.c tiget.c 
+BUILT=	term.h keycaps curses.h keyname.c termcap.c tiget.c tnames.c tinames.c tifnames.c tifget.c
 LINT=	lint
 LPASS1=	/usr/lib/lint1
-TMP=	$(ROOT)/usr/tmp
+TMP=	./tmp
 DESTDIR = $(ROOT)
 AR=	TMPDIR=$(TMP) ar
 RM=	rm
@@ -37,74 +37,118 @@ LIBS=
 SHELL=	/bin/sh
 .SUFFIXES: .p .d .t
 
-HEADERS=curses.h unctrl.h curses.ext curshdr.h term.h uparm.h
+HEADERS=curses.h unctrl.h curses_inc.h curshdr.h term.h uparm.h
 
-# The following order of .c files was generated by hand, and assumes
-# that either setupterm or initscr is called first by the user program.
-# It only matters on older SYSV systems (4.0 or earlier) or on the
-# PDP-11; since 32 bit 5.0 has a table of contents in the archive.
-# This order works on an 11/70 running an early 6.0.
-CFILES=	initscr.c newterm.c setterm.c gettmode.c subwin.c newpad.c \
-	makenew.c setupterm.c reset_sh.c def_prog.c saveterm.c fixterm.c \
-	resetterm.c fixdelay.c baudrate.c halfdelay.c cbreak.c clearok.c \
-	crmode.c echo.c erasechar.c has_ic.c has_il.c idlok.c intrflush.c \
-	keypad.c killchar.c leaveok.c meta.c nl.c nocbreak.c nocrmode.c \
-	nodelay.c noecho.c nonl.c noraw.c notimeout.c raw.c resetty.c \
-	savetty.c scrollok.c typeahead.c refresh.c endwin.c ll_refresh.c \
-	ll_sub.c ll_scrdown.c trm.c insdelchar.c insdelline.c overwrite.c \
-	scanw.c wscanw.c pos.c beep.c ll_trm.c flushinp.c restart.c \
-	overlay.c mvprintw.c mvwprintw.c printw.c wprintw.c getstr.c getch.c \
-	copywin.c addstr.c addch.c insch.c insertln.c scroll.c \
-	m_addstr.c m_addch.c m_clear.c m_erase.c \
-	m_initscr.c m_move.c m_newterm.c m_refresh.c \
-	wechochar.c pechochar.c ll_echo.c pnoutref.c wnoutref.c doupdate.c \
-	mvscanw.c mvwscanw.c delay_out.c ll_newtty.c ll_init.c initkeypad.c \
-	putp.c clear.c vidputs.c mvcur.c mvwin.c longname.c box.c \
-	termcap.c tgoto.c tparm.c tputs.c tiget.c \
-	cio.c capnames.c clrtobot.c clrtoeol.c \
-	curses.c delch.c deleteln.c delwin.c erase.c \
-	move.c standout.c wattroff.c wattron.c wattrset.c touchwin.c tstp.c \
-	unctrl.c vwprintw.c vwscanw.c chkinput.c \
-	slk_clear.c slk_init.c slk_label.c slk_nout.c \
-	slk_ref.c slk_rest.c slk_set.c slk_touch.c \
-	ungetch.c memSset.c curs_set.c delay.c draino.c ec_quit.c flash.c \
-	getsyx.c napms.c prefresh.c ripoffline.c set_term.c setsyx.c subpad.c \
-	touchline.c trace.c scr_dump.c scr_rest.c scr_init.c garbaged.c \
-	keyname.c vsscanf.c V2.makenew.c V2._sprintw.c V2.__sscans.c \
-	set_TERM.c del_TERM.c
-
+#
+#	tic source and header files
+#
 TICHDRS= compiler.h object.h
 TICSRC= tic_main.c tic_hash.c tic_captab.c tic_scan.c tic_error.c \
-	tic_parse.c tic_read.c capnames.c
-
+	tic_parse.c tic_read.c tnames.c tinames.c tifnames.c
 TICOBJS= $(TICSRC:.c=.o)
 
 CHDRS= print.h otermcap.h
+
 BSRC= print.c iexpand.c
 BOBJ= print.o iexpand.o
+
 CSRC= captoinfo.c otermcap.c $(BSRC)
 COBJ= captoinfo.o otermcap.o $(BOBJ)
+
 ISRC= infocmp.c cexpand.c infotocap.c $(BSRC)
 IOBJ= infocmp.o cexpand.o infotocap.o $(BOBJ)
 
-all: $(SLIB) llib-lcurses.ln tools
+tools: $(SLIB) tic tput captoinfo infocmp show dumpti chgtinfo
 
-tools: $(SLIB) tic tput captoinfo infocmp show dumpti
+CFILES1=_addch.c _addchnstr.c _addchstr.c _addnstr.c _addstr.c \
+	_attroff.c _attron.c _attrset.c _beep.c _bkgd.c \
+	_bkgdset.c _border.c _box.c _clear.c _clrtobot.c \
+	_clrtoeol.c _crmode.c _del_curterm.c _delch.c _deleteln.c \
+	_echo.c _echochar.c _erase.c _fixterm.c _flash.c \
+	_garbagdlins.c _garbagedwin.c _getch.c _getstr.c \
+	_halfdelay.c _hline.c _inch.c _inchnstr.c _inchstr.c \
+	_innstr.c _insch.c _insdelln.c _insertln.c _insnstr.c \
+	_insstr.c _instr.c _intrflush.c _meta.c _move.c \
+	_mvaddch.c _mvaddchnstr.c _mvaddchstr.c _mvaddnstr.c \
+	_mvaddstr.c _mvdelch.c _mvgetch.c _mvgetstr.c _mvhline.c \
+	_mvinch.c _mvinchnstr.c _mvinchstr.c _mvinnstr.c \
+	_mvinsch.c _mvinsnstr.c _mvinsstr.c _mvinstr.c _mvvline.c \
+	_mvwaddch.c _mvwaddchnst.c _mvwaddchstr.c _mvwaddnstr.c \
+	_mvwaddstr.c _mvwdelch.c _mvwgetch.c _mvwgetstr.c \
+	_mvwhline.c _mvwinch.c _mvwinchnst.c _mvwinchstr.c \
+	_mvwinnstr.c _mvwinsch.c _mvwinsnstr.c _mvwinsstr.c \
+	_mvwinstr.c _mvwvline.c _newterm.c _nl.c _nocrmode.c \
+	_noecho.c _nonl.c _noqiflush.c _overlay.c _overwrite.c \
+	_qiflush.c _refresh.c _resetterm.c _saveterm.c \
+	_scr_init.c _scr_restore.c _scr_set.c _scrl.c _scroll.c \
+	_set_curterm.c _set_term.c _setscrreg.c _slk_init.c \
+	_standend.c _standout.c _subpad.c _timeout.c _touchline.c \
+	_unctrl.c _vline.c _waddchstr.c _waddstr.c _wclear.c \
+	_wdeleteln.c _werase.c _winsertln.c _winsstr.c \
+	_wstandend.c _wstandout.c V2.__sscans.c V2._sprintw.c \
+	V2.makenew.c V3.box.c V3.initscr.c V3.m_addch.c V3.m_addstr.c \
+	V3.m_clear.c V3.m_erase.c V3.m_initscr.c V3.m_move.c V3.m_newterm.c \
+	V3.m_refresh.c V3.newterm.c V3.pechochar.c V3.upd_old_y.c \
+	V3.vidattr.c V3.vidputs.c V3.waddch.c V3.wattroff.c V3.wattron.c \
+	V3.wattrset.c V3.wechochar.c V3.winsch.c baudrate.c cbreak.c \
+	chkinput.c clearok.c copywin.c curs_set.c \
+	curserr.c curses.c def_prog.c delay.c delay_out.c \
+	delkey.c delkeymap.c delscreen.c delterm.c delwin.c \
+	derwin.c doupdate.c draino.c dupwin.c endwin.c \
+	erasechar.c flushinp.c getattrs.c getbegyx.c getbkgd.c \
+	getmaxyx.c getparyx.c getsyx.c gettmode.c getwin.c \
+	getyx.c has_ic.c has_il.c idcok.c idlok.c \
+	immedok.c init_acs.c init_costs.c initscr.c is_linetou.c \
+	is_wintou.c keyname.c keypad.c killchar.c leaveok.c
+
+CFILES2=longname.c makenew.c memSset.c meta.c mvcur.c \
+	mvderwin.c mvprintw.c mvscanw.c mvwin.c mvwprintw.c \
+	mvwscanw.c napms.c newkey.c newpad.c newscreen.c \
+	newwin.c nocbreak.c nodelay.c noraw.c \
+	notimeout.c outch.c overlap.c pechochar.c pnoutref.c \
+	prefresh.c printw.c putp.c putwin.c quick_echo.c \
+	raw.c redrawwin.c reset_sh.c resetty.c restart.c \
+	ring.c ripoffline.c savetty.c scanw.c scr_all.c \
+	scr_dump.c scr_ll_dump.c scr_reset.c scrollok.c setcurscreen.c \
+	setcurterm.c setecho.c setkeymap.c setnonl.c setqiflush.c \
+	setsyx.c setterm.c setupterm.c slk_clear.c slk_label.c \
+	slk_noutref.c slk_refresh.c slk_restore.c slk_set.c slk_start.c \
+	slk_touch.c subwin.c syncok.c tcsearch.c termattrs.c \
+	termcap.c termerr.c termname.c tgetch.c tgoto.c \
+	tifget.c tifnames.c tiget.c tinames.c tinputfd.c \
+	tnames.c touchwin.c tparm.c tputs.c trace.c \
+	tstp.c ttimeout.c typeahead.c unctrl.c ungetch.c \
+	untouchwin.c vidputs.c vidupdate.c vsscanf.c vwprintw.c \
+	vwscanw.c waddch.c waddchnstr.c waddnstr.c wattroff.c \
+	wattron.c wattrset.c wbkgd.c wbkgdset.c wborder.c \
+	wclrtobot.c wclrtoeol.c wdelch.c wechochar.c wgetch.c \
+	wgetstr.c whline.c winch.c winchnstr.c winchstr.c \
+	winnstr.c winsch.c winsdelln.c winsnstr.c winstr.c \
+	wmove.c wnoutref.c wprintw.c wredrawln.c wrefresh.c \
+	wscanw.c wscrl.c wsetscrreg.c wsyncdown.c wsyncup.c \
+	wtimeout.c wtouchln.c wvline.c
+
+all: date $(SLIB) llib-lcurses.ln tools
+ 
+date:
+	@echo Started: `date`
 
 # Regular, optimized objects
-OBJS=	$(CFILES:.c=.o)
-$(OBJS): ${HEADERS}
+OBJS1=	$(CFILES1:.c=.o)
+OBJS2=	$(CFILES2:.c=.o)
+$(OBJS1): ${HEADERS}
+$(OBJS2): ${HEADERS}
 
 # Profiled, optimized objects
-POBJS=	$(CFILES:.c=.p)
-$(POBJS): ${HEADERS}
+#POBJS=	$(CFILES:.c=.p)
+#$(POBJS): ${HEADERS}
 
 # Debugging objects
-DOBJS=	$(CFILES:.c=.d)
-$(DOBJS): ${HEADERS}
+#DOBJS=	$(CFILES:.c=.d)
+#$(DOBJS): ${HEADERS}
 
 # Tracing objects
-# TOBJS=	$(CFILES:.c=.t)
+#TOBJS=	$(CFILES:.c=.t)
 #$(TOBJS): ${HEADERS}
 
 .c.p:
@@ -123,21 +167,16 @@ $(DOBJS): ${HEADERS}
 	mv $*.o $*.t
 	-mv $*.O $*.o
 
-dumpti: $(SLIB) setupterm.c
-	@echo
-	@echo Building dumpti
-	@echo
-	ln setupterm.c dumpti.c
-	$(CC) $(CFLAGS) -DDUMPTI -s dumpti.c $(SLIB) -o dumpti ; rm dumpti.c
-	@echo
-	@echo dumpti has been built
-	@echo
+obj1:	$(OBJS1)
 
-$(SLIB): ${OBJS}
+obj2:	$(OBJS2)
+
+$(SLIB): obj1 obj2
 	@echo
 	@echo Building libcurses archive
 	@echo
-	${AR} rv $(SLIB) $?
+	${AR} rv $(SLIB) $(OBJS1)
+	${AR} rv $(SLIB) $(OBJS2)
 	@echo
 	@echo libcurses has been archived
 	@echo
@@ -157,36 +196,18 @@ t$(SLIB): ${OBJS}
 	rm -f x.c
 	${AR} rv t$(SLIB) $?
 
-captoinfo: $(COBJ) $(SLIB)
-	$(CC) $(COBJ) $(SLIB) -s -o captoinfo
-
-infocmp: $(IOBJ) $(SLIB)
-	$(CC) $(IOBJ) $(SLIB) -s -o infocmp
-
-captoinfo.o:	captoinfo.c curses.h otermcap.h print.h
-otermcap.o:	otermcap.c otermcap.h
-print.o:	print.c curses.h print.h
-iexpand.o:	iexpand.c print.h
-cexpand.o:	cexpand.c print.h
-infotocap.o:	infotocap.c curses.h
-infocmp.o:	infocmp.c curses.h term.h print.h
-
-tic_captab.o:	tic_captab.c compiler.h
-tic_error.o:	tic_error.c compiler.h
-tic_hash.o:	tic_hash.c compiler.h
-tic_main.o:	tic_main.c compiler.h
-tic_parse.o:	tic_parse.c compiler.h object.h
-tic_read.o:	tic_read.c object.h
-tic_scan.o:	tic_scan.c compiler.h
-
-setupterm.o: term.h
-term.h capnames.c: caps maketerm.ed
+setupterm.o: term.h 
+term.h tnames.c tinames.c tifnames.c: caps maketerm.ed
+	@if [ ! -d "$(TMP)" ] ;\
+	then	echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
+	fi;
 	@echo
 	@echo Building term.h
 	@echo
-	rm -f term.h capnames.c
 	ed - < maketerm.ed
-	chmod a-w term.h capnames.c
+	$(CH) chmod 0664 term.h tnames.c tinames.c tifnames.c
 	@echo
 	@echo "term.h has been built"
 	@echo
@@ -195,66 +216,87 @@ keycaps: caps
 	@echo
 	@echo Building keycaps
 	@echo
-	grep "KEY_" caps > $(TMP)/keycaps
-	if cmp -s $(TMP)/keycaps keycaps;then :;else cp $(TMP)/keycaps keycaps;fi
-	rm -f $(TMP)/keycaps
+	rm -rf $(TMP)/keycaps keycaps
+	grep "KEY_" caps > keycaps
 	@echo 
 	@echo "keycaps has been built"
 	@echo
 
-curses.h: keycaps curses.form curses.ed
+curses.h: keycaps curses.ed
+	@if [ ! -d "$(TMP)" ] ;\
+	then	echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
+	fi;
 	@echo 
 	@echo Building ./curses.h
 	@echo 
 	rm -f curses.h
 	ed - < curses.ed
-	chmod -w curses.h
+	$(CH) chmod 0664 curses.h
+	rm -rf $(TMP)/keycaps
 	@echo 
 	@echo "curses.h has been built"
 	@echo 
 
-keyname.c: keycaps keyname.ed
+keyname.c: keycaps keyname.sh
 	@echo
 	@echo Building keyname.c
 	@echo
 	rm -f keyname.c
-	ed - < keyname.ed
-	chmod -w keyname.c
+	sh keyname.sh
+	$(CH) chmod 0664 keyname.c
 	@echo
 	@echo "keyname.c has been built"
 	@echo
 
-initkeypad.c: keycaps initkeypad.ed
-	@echo
-	@echo Building initkeypad.c
-	@echo
-	rm -f initkeypad.c
-	ed - < initkeypad.ed
-	chmod -w initkeypad.c
-	@echo
-	@echo "initkeypad.c has been built"
-	@echo
+setkeymap.c: keycaps
+	@if tail -1 keycaps | grep 'KEY_F(63)' > /dev/null;then :; \
+		else echo new keys!! must change setkeymap.c; exit 1;fi
 
-termcap.c:	termcap.form termcap.ed caps
+termcap.c:	termcap.ed caps
+	@if [ ! -d "$(TMP)" ] ;\
+	then	echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
+	fi;
 	@echo 
 	@echo Building termcap.c
 	@echo
 	rm -f termcap.c
 	ed - < termcap.ed
 	rm -f bool num str
-	chmod -w termcap.c
+	$(CH) chmod 0664 termcap.c
 	@echo 
 	@echo "termcap.c has been built"
 	@echo
 
+tifget.c:	tifget.ed caps
+	@if [ ! -d "$(TMP)" ] ;\
+	then	echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
+	fi;
+	@echo
+	@echo Building tifget.c
+	@echo
+	ed - < tifget.ed
+	$(CH) chmod 0664 tifget.c
+	@echo
+	@echo "tifget.c has been built"
+	@echo
+
 tiget.c:	tiget.ed caps
+	@if [ ! -d "$(TMP)" ] ;\
+	then	echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
+	fi;
 	@echo
 	@echo Building tiget.c
 	@echo
-	rm -f tiget.c
-	cat /dev/null > tiget.c
 	ed - < tiget.ed
-	chmod -w tiget.c
+	$(CH) chmod 0664 tiget.c
 	@echo
 	@echo "tiget.c has been built"
 	@echo
@@ -262,41 +304,13 @@ tiget.c:	tiget.ed caps
 ticclob:
 	rm -rf ${TICOBJS} tic
 
-tic: ${TICOBJS}
-	@echo
-	@echo Building the tic compiler
-	@echo
-	${CC} -s -o tic ${TICOBJS}
-	@echo
-	@echo the tic compiler has been built
-	@echo
-
-otic: otic.o capnames.o unctrl.o
-	${CC} -s -o otic otic.o capnames.o unctrl.o
-
-linttic: ${TICSRC}
-	${LINT} ${CPPDEFS} ${TICSRC}
-
-lintinfocmp: ${ISRC}
-	${LINT} ${CPPDEFS} ${ISRC}
-
-lintcaptoinfo: ${CSRC}
-	${LINT} ${CPPDEFS} ${CSRC}
-
-show:	$(SLIB) show.o
-	${CC} ${LDFLAGS} ${CFLAGS} -s -o show show.o $(SLIB)
-pshow:	p$(SLIB) show.p
-	${CC} ${LDFLAGS} -pg ${CFLAGS} -o pshow show.p p$(SLIB)
-dshow:	d$(SLIB) show.d
-	${CC} ${LDFLAGS} ${DFLAGS} -o dshow show.d d$(SLIB)
-tshow:	t$(SLIB) show.t
-	${CC} ${LDFLAGS} ${TFLAGS} -o tshow show.t t$(SLIB)
-
-tput:	$(SLIB) tput.o
-	${CC} ${LDFLAGS} ${CFLAGS} -s -o tput tput.o $(SLIB)
-
-testterminfo:	$(SLIB) testterminfo.o
-	${CC} ${LDFLAGS} ${CFLAGS} -s -o testterminfo testterminfo.o $(SLIB)
+tic_captab.o:	tic_captab.c compiler.h
+tic_error.o:	tic_error.c compiler.h
+tic_hash.o:	tic_hash.c compiler.h
+tic_main.o:	tic_main.c compiler.h curses.h
+tic_parse.o:	tic_parse.c compiler.h object.h
+tic_read.o:	tic_read.c object.h
+tic_scan.o:	tic_scan.c compiler.h
 
 new:	clean tags $(SLIB)
 
@@ -308,7 +322,8 @@ clean:
 	@echo
 	@echo "Removing all .o's"
 	@echo
-	@rm -f ${OBJS} $(SLIB)
+	@rm -f $(OBJS1) $(SLIB)
+	@rm -f $(OBJS2)
 	@echo
 	@echo "Removing all .d's"
 	@echo
@@ -324,9 +339,8 @@ clean:
 	rm -rf $(BUILT)
 
 clobber: clean
-	@rm -rf ${TOBJS} t$(SLIB) $(SLIB) ?$(SLIB)
-	rm -rf infocmp show scr page one two cat captoinfo dumpti testterminfo tput tic
-	rm -rf llib-lcurses.ln
+	@rm -rf ${TOBJS} t$(SLIB) $(SLIB) ?$(SLIB) $(TMP)
+	rm -rf captoinfo chgtinfo dumpti infocmp show llib-lcurses.ln tic tput 
 
 rmhdrs: 
 	@echo
@@ -355,10 +369,10 @@ TPFILES= makefile makefile.bsd makefile.sysv \
 	${HEADERS} ${CFILES} \
 	${TICHDRS} ${TICSRC} \
 	${CHDRS} ${BSRC} ${CSRC} ${ISRC} \
-	curses.ed curses.form ns_curses.h \
-	termcap.ed termcap.form maketerm.ex tiget.ed \
-	tags llib-lcurses TODO caps getopt.c initkeypad.ed \
-	keyname.ed otic.c \
+	curses.ed \
+	termcap.ed tiget.ed tifget.ed \
+	tags llib-lcurses TODO caps getopt.c \
+	keyname.sh otic.c \
 	show.c testterminfo.c tput.c
 
 tp:
@@ -377,16 +391,15 @@ cpiotape:
 	ls ${TPFILES} | uniq | cpio -oBc > /dev/rmt8
 
 llib-lcurses.ln: llib-lcurses
-	$(CC) -E -C -I. -Dlint llib-lcurses | ${LPASS1} -vx -H/usr/tmp/hlint > llib-lcurses.ln
-	rm -f /usr/tmp/hlint
+	$(CC) -E -C -I. -Dlint llib-lcurses | ${LPASS1} -vx -H$(TMP)/hlint > llib-lcurses.ln
+	rm -f $(TMP)/hlint
 
 install:	all
 	cpset $(SLIB) $(USRLIB) 644 bin bin
 	cp curses.h term.h unctrl.h $(DESTDIR)/usr/include
 	@if [ -d "$(INC)" ] ;\
-		then \
-			cp curses.h term.h unctrl.h $(INC) ;\
-	fi;
+	then	cp curses.h term.h unctrl.h $(INC) ;\
+	fi
 	rm -f $(USRLIB)/libtermcap.a
 	ln $(USRLIB)/libcurses.a $(USRLIB)/libtermcap.a
 	ln $(USRLIB)/libcurses.a $(USRLIB)/libtermlib.a
@@ -403,13 +416,77 @@ cktmp:
 	@echo Verifying the existence of $(TMP).
 	@echo
 	@if [ -d "$(TMP)" ] ;\
-		then \
-			echo "\t$(TMP) exists";\
-			echo;\
-		else  \
-			echo "\t$(TMP) not found.";\
-			echo "\n\tchange the following line of the makefile and re-run\n\n\t\t\c";\
-			grep "TMP=" makefile|grep -v makefile;\
-			echo;\
-			exit 1;\
+	then \
+		echo "\t$(TMP) exists";\
+		echo;\
+	else  \
+		echo "\t$(TMP) not found.";\
+		echo "\n\tCreating $(TMP)\n";\
+		mkdir $(TMP); \
 	fi;
+
+dumpti: setupterm.c curses.h term.h tnames.o tinames.o tifnames.o termerr.o
+	@echo
+	@echo Building dumpti
+	@echo
+	ln setupterm.c dumpti.c
+	$(CC) $(CFLAGS) -DDUMPTI -s dumpti.c tnames.o tinames.o tifnames.o termerr.o -o dumpti ; rm -rf dumpti.c
+	@echo
+	@echo dumpti has been built
+	@echo
+
+captoinfo: $(COBJ) $(SLIB)
+	$(CC) $(COBJ) $(SLIB) -s -o captoinfo
+
+infocmp: $(IOBJ) $(SLIB)
+	$(CC) $(IOBJ) $(SLIB) -s -o infocmp
+
+captoinfo.o:	captoinfo.c curses.h otermcap.h print.h
+otermcap.o:	otermcap.c otermcap.h
+print.o:	print.c curses.h print.h
+iexpand.o:	iexpand.c print.h
+cexpand.o:	cexpand.c print.h
+infotocap.o:	infotocap.c curses.h
+infocmp.o:	infocmp.c curses.h term.h print.h
+
+tic: ${TICOBJS}
+	@echo
+	@echo Building the tic compiler
+	@echo
+	${CC} -s -o tic ${TICOBJS}
+	@echo
+	@echo the tic compiler has been built
+	@echo
+
+otic: otic.o tnames.o tinames.o tifnames.o unctrl.o
+	${CC} -s -o otic otic.o tnames.o tinames.o tifnames.o unctrl.o
+
+linttic: ${TICSRC}
+	${LINT} ${CPPDEFS} ${TICSRC}
+
+lintinfocmp: ${ISRC}
+	${LINT} ${CPPDEFS} ${ISRC}
+
+lintcaptoinfo: ${CSRC}
+	${LINT} ${CPPDEFS} ${CSRC}
+
+show:	$(SLIB) show.o
+	${CC} ${LDFLAGS} ${CFLAGS} -o show show.o $(SLIB)
+
+pshow:	p$(SLIB) show.p
+	${CC} ${LDFLAGS} -pg ${CFLAGS} -o pshow show.p p$(SLIB)
+
+dshow:	d$(SLIB) show.d
+	${CC} ${LDFLAGS} ${DFLAGS} -o dshow show.d d$(SLIB)
+
+tshow:	t$(SLIB) show.t
+	${CC} ${LDFLAGS} ${TFLAGS} -o tshow show.t t$(SLIB)
+
+tput:	$(SLIB) tput.o tnames.o tinames.o tifnames.o
+	${CC} ${LDFLAGS} ${CFLAGS} -o tput tput.o $(SLIB)
+
+testterminfo:	$(SLIB) testterminfo.o
+	${CC} ${LDFLAGS} ${CFLAGS} -o testterminfo testterminfo.o $(SLIB)
+
+chgtinfo:	curses.h chgtinfo.c
+	${CC} ${LDFLAGS} ${CFLAGS} -o chgtinfo chgtinfo.c
diff --git a/usr/src/scripts/nsu/setup b/usr/src/scripts/nsu/setup
--- a/usr/src/scripts/nsu/setup
+++ b/usr/src/scripts/nsu/setup
@@ -1,4 +1,4 @@
-#ident	"@(#)pkg.nsu:setup	1.4"
+#ident	"@(#)pkg.nsu:setup	1.7.1.3"
 #
 #	Setup script for AT&T NSU Package for AT&T 3B2 Computer.
 #
@@ -20,7 +20,7 @@ rm -rf /dev/log
 # Install the TIMOD module
 #
 
-/etc/drvinstall -d /boot/timod.o -v 1.0 -c 16
+/etc/drvinstall -d /boot/timod.o -v 1.0 -c 32
 
 #
 # Install the TIRDWR module
@@ -36,8 +36,8 @@ touch /etc/system
 
 ed - /etc/master.d/kernel <<!
 /^NCALL/s/= [0-9][0-9]*$/= 60/
-/^NSTREAM/s/= [0-9][0-9]*$/= 32/
-/^NQUEUE/s/= [0-9][0-9]*$/= 256/
+/^NSTREAM/s/= [0-9][0-9]*$/= 36/
+/^NQUEUE/s/= [0-9][0-9]*$/= 288/
 /^NMUXLINK/s/= [0-9][0-9]*$/= 32/
 /^NSTREVENT/s/= [0-9][0-9]*$/= 256/
 /^MAXSEPGCNT/s/= [0-9][0-9]*$/= 1/
@@ -70,3 +70,22 @@ if  grep listen /etc/passwd
 	else
 	echo "listen:np:37:4:Network Admin:/usr/net/nls" >>/etc/passwd
 fi
+LHOME=/usr/net/nls
+chown root $LHOME; chgrp sys $LHOME
+for i in $LHOME/*
+do
+	chown root $i; chgrp sys $i
+	if test -d $i
+	then
+		chown root $i/*; chgrp sys $i/*
+		if test -f $i/dbf
+		then
+			cp $i/dbf $i/odbf
+			/usr/net/nls/dbfconv $i/odbf $i/dbf
+			if [ $? -ne 0 ]
+			then
+				echo "**ERROR** listener database conversion failed"
+			fi
+		fi
+	fi
+done
